### ISSUE TITLE
Please add requirements.txt with versions and fix xgboost model loading

### ISSUE THREAD

**Issue by MakarovS96** [tyewu/IRIS-Database-and-Machine-Learning-Based-Approaches-for-Prediction-of-Spontaneous-Intracerebral-Hemo#1]
I can't load xgboost model 
I tried on lastest(1.5.2) version. Python version 3.10.

<img width="773" alt="image" src="https://user-images.githubusercontent.com/19629483/155395350-7af3b078-889d-4c64-ac9d-721c1a658b0a.png">

My venv packages
<img width="436" alt="image" src="https://user-images.githubusercontent.com/19629483/155398691-dc8c090d-d2a7-42ca-bcc7-c13df661d220.png">

**Comment by tyewu** [comment]
Thanks for your reminder. I have updated the model file and project.py , please enjoy it.

**Comment by MakarovS96** [comment]
What about requirements.txt file? This is file with required packages and versions
https://note.nkmk.me/en/python-pip-install-requirements/
"xgboost pyodbc flask pandas numpy joblib sklearn requests" - you should to add this packages to requirements.txt

**Comment by tyewu** [comment]
Requirements.txt has been uploaded, sorry for not creating a separate virtual environment due to the competition time. This is the python package in my system, including the version of the Python package used in the competition

**Comment by tyewu** [comment]
pyodbc==4.0.26
xgboost==1.5.2
Flask==1.0.2
pandas==0.24.2
numpy==1.19.5
scikit-learn==0.22.2.post1
requests==2.21.0

**Comment by tyewu** [comment]
Since the model is called with the new version, no joblib package is needed

**Comment by MakarovS96** [comment]
Nice, thank you!

**Comment by tyewu** [comment]
You're welcome, thank you very much!
